# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup and run tests
        working-directory: ./app
        run: |
          wget --output-document my.yaml https://dev-dist-api.ebullion.in/docs/yaml
          cat my.yaml
      - uses: actions/setup-java@v2
        with:
            distribution: temurin
            java-version: 8

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
           gradle-version: 4.10
      - run: gradle build --stacktrace # just test build configuration
      - run: gradle run --stacktrace # just test build configuration
         
            
